---
title: "ques2_3"
author: "Somya Singhal(S3813520)"
date: "29/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
library(tidyr)
library(dplyr)
library(readr)
library(readxl)
library(magrittr)
library(lattice)
library(ggplot2)
library(lubridate)


#South korea, new zealand,iceland,australia,greece
#2)As a government, I want to know how GDP is affecting to figure out some other measures to improve the conditions.
#3)As a government, I want to know how the stringent measures is related to total deaths.


covid_data <- read_csv("covid-data.csv")
data <- read_excel("D2019-20.xlsx")
degree<-data%>% filter(`Degree of volatility`=="High Volatility Expected" & Date >= "2020/01/01")
trade <- read_csv("Trade.csv")

#plot cases
c<-covid_data %>% filter(location == 'South Korea' | location == 'New Zealand'
                                     | location == 'Iceland'| location == 'Australia'
                                     | location == 'Greece')


comb<-covid_data %>% filter((location == 'South Korea' | location == 'New Zealand'
                         | location == 'Iceland'| location == 'Australia'
                         | location == 'Greece' ) &  date=="2020-08-11")

unique(trade$Direction)
unique(trade$Year)


```
```{r cars}

bse_stock <- read_csv("Dataset/Stockmarket/BSE.csv")
bse_stock <- read_csv("Dataset/Stockmarket/BSE.csv")
bse_stock <- read_csv("Dataset/Stockmarket/BSE.csv")
bse_stock <- read_csv("Dataset/Stockmarket/BSE.csv")
bse_stock <- read_csv("Dataset/Stockmarket/BSE.csv")
bse_stock <- read_csv("Dataset/Stockmarket/BSE.csv")
bse_stock <- read_csv("Dataset/Stockmarket/BSE.csv")


```

```{r}


#ques 2

ggplot(comb,aes(x=gdp_per_capita,y=total_cases,colour=location,group=location,fill=location))+
  geom_point()+
  scale_y_continuous(breaks = seq(0,50000,10000)) +
  labs(title = " Effect on GDP of different countries based on total cases",
       x = "GDP",
       y = "Total cases") +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))
  

  


#ques3

ggplot(c,aes(x=stringency_index,y=total_cases,colour=location,group=location,fill=location))+
  geom_line(size = 0.7)+
  scale_y_continuous(breaks = seq(0,50000,10000)) +
  labs(title = " Effect of stringent measures on covid cases",
       x = "stringency index",
       y = "The number of total cases") +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))


#ques 7

ggplot(degree, 
       aes(x = Even, 
           fill = `Degree of volatility`)) + 
  geom_bar(position = "dodge")+
labs(title = " events affecting volatlity",
     x = "events",
     y = " count") +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))


#extra


ggplot(degree, 
       aes(x = Even, 
           fill = Country)) + 
  geom_bar(position = "dodge")+
  labs(title = " events affecting volatlity in different countries",
       x = "events",
       y = " count") +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5))


##trade

#trade


ggplot(data = trade, aes(x=Year, y=Cumulative)) + geom_boxplot(aes(fill=Direction))+
  facet_wrap( ~ Year, scales="free") +
  xlab("Year") + ylab(" $ Value") + ggtitle("Impact on export and import")



```
